### ISSUE TITLE
Better name for `isDown` for the sake of clarity

### ISSUE THREAD

**Issue by omgmog** [ericoporto/ktg#1]
Hey this looks like a very useful library.

I noticed in your examples in the README that you have a method called `isDown`, which when used can give you a case such as:

`ktg.isDown(ktg.key.UP)`

Or

`ktg.isDown(ktg.key.DOWN)`

Now, at a glance the first example might _sound_ like it's falsey, because up is not down, where as the second sounds truthy. I propose that you use a different name for this method such as `isPressed`, which holds the same meaning but with less confusion bias.

`ktg.isPressed(ktg.key.UP)`

`ktg.isPressed(ktg.key.DOWN)`

:boom:

Cheers!

**Comment by omgmog** [comment]
Additionally, `keyUp` and `keyDown` events might be better as `keyPressed` and `keyReleased`, but I think that's less of an issue.

**Comment by ericoporto** [comment]
Hey @omgmog , thank you for your suggestion, they were very good and I already changed the names to reflect what you have said. I think the new names make more sense! Closing this issue.
